# Generated by Django 4.2.8 on 2023-12-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundoarte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produtc',
            new_name='Product',
        ),
    ]
