# Generated by Django 4.2.8 on 2023-12-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundoarte', '0002_rename_produtc_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='name',
            new_name='nome',
        ),
    ]
