# Generated by Django 4.2.8 on 2023-12-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundoarte', '0003_rename_category_categoria_rename_name_categoria_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Subcategoria',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='name',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
