# Generated by Django 4.2.8 on 2023-12-18 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mundoarte', '0004_rename_subcategory_subcategoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='publicated',
            new_name='publicada',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='subcategory',
            new_name='subcategoria',
        ),
    ]
