# Generated by Django 4.2.8 on 2023-12-19 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundoarte', '0005_rename_product_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
